version: "3"

vars:
  site_dir: website
  site_url: https://net-auto.nl
  rfp_form_url: https://forms.gle/qmjaMqcHLuJV3rTy8
  upcoming_event_filename:
    sh: |
      # Get current date in YYYYMMDD format
      current_date=$(date +%Y%m%d)

      # Find the next upcoming event file
      upcoming_file=$(find {{.site_dir}}/docs/events/dates/ -name "*.md" -type f | \
        while read file; do
          filename=$(basename "$file")
          file_date=$(echo "$filename" | cut -d'_' -f1)
          if [[ "$file_date" > "$current_date" ]]; then
            echo "$file_date:$file"
          fi
        done | sort | head -1 | cut -d':' -f2)
        filename=$(basename "$upcoming_file" .md)
        if [[ -z "$filename" ]]; then
          echo "No upcoming events found in {{.site_dir}}/docs/events/dates/"
          exit 1
        fi
        echo "$filename"
  upcoming_event_date:
    sh: echo "{{.upcoming_event_filename}}" | cut -d'_' -f1
  upcoming_event_sponsor:
    sh: echo "{{.upcoming_event_filename}}" | cut -d'_' -f2- | cut -d'.' -f1
  upcoming_date_formatted:
    sh: |
      raw_date="{{.upcoming_event_date}}"
      echo "${raw_date:0:4}-${raw_date:4:2}-${raw_date:6:2}"

tasks:
  default: task -l --sort none

  build:
    desc: Build the site
    dir: "{{.site_dir}}"
    cmd: |
      export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
      uv run mkdocs build -v --strict -t material

  test:
    desc: Run the github test workflow with act
    cmds:
      - act -j test

  test:pytest:
    desc: Run pytest
    dir: website
    cmds:
      - uv run pytest -v

  deploy:
    desc: Deploy the site to GitHub Pages branch
    aliases: [delpoy]
    prompt:
      - This actually deploys the site. Do you want to continue?
    cmds:
      - uv run mkdocs gh-deploy --force

  serve:
    desc: Serve the site
    dir: website
    cmd: |
      export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
      open http://localhost:8000/
      uv run mkdocs serve

  ### Initialize the repo
  init:
    desc: Initialize this repo install all dependencies for uv and mac
    cmds:
      - task: init:uv
      - task: init:mac

  init:uv:
    desc: Initialize this repo with python dependencies with uv
    cmds:
      - uv sync

  init:mac:
    desc: Initialize this repo with mac dependencies
    platforms:
      - darwin
    cmds:
      - brew install cairo freetype libffi libjpeg libpng zlib pngquant

  event:
    desc: Create a new event and open it in vscode
    aliases: [new, post]
    silent: true
    interactive: true
    cmd: |
      echo "Provide the date in format YYYY-MM-DD for the next event:"
      read event_date
      echo "Provide the sponsor of the next event (without spaces, in the desired case):"
      read event_sponsor
      echo "What is the website? (full: https://net-auto.nl)"
      read event_website
      echo "What is the full address? (used for Gmaps link)"
      read event_address
      event_sponsor_lower=$(echo "$event_sponsor" | tr '[:upper:]' '[:lower:]')
      event_file="{{.site_dir}}/docs/events/dates/$(echo "$event_date" | sed 's/-//g')_${event_sponsor}.md"
      sponsors=$(sed 's/_/ \& /g' <<< "$event_sponsor")

      cat << EOF >> $event_file
      ---
      # draft: true
      date:
        created: {{ now.Format "2006-01-02" }}
        # updated: {{ now.Format "2006-01-02" }}
      title: NLNAM Meetup
      description: $event_date NLNAM Meetup event
      ---

      # NLNAM Meetup with $sponsors

      The next meetup is hosted by [$sponsors]($event_website) on $event_date.

      Thank you $sponsors for opening your doors to host us and fill our bellies with pizzas and drinks!

      * [Register for the event](https://nlnam_${event_sponsor_lower}.eventbrite.nl/)
          * Registration ends on {\{ get_older_date("$event_date", 1) }} at 23:59.
      * [Submit a presentation proposal]({{.rfp_form_url}})
          * Talks will be selected and communicated around {\{ get_older_date("$event_date", 30) }}.

      ## Specifics
      * [OPTIONAL] **<u>Bring your ID</u>** to enter the building.
      * [OPTIONAL] We have a hard stop at 21:30. We will need to be outside the building by then.
      * Parking is TODO not available

      ## Location
      {\{ google_maps_link("$event_address") }}

      ## Agenda

      | Time  | Activity                                      |
      | ----- | --------------------------------------------- |
      | 18:00 | Doors open                                    |
      | 18:25 | Welcome + **$event_sponsor** sponsor talk     |
      | 19:00 | Talk 1                                        |
      | 19:30 | Talk 2                                        |
      | 20:00 | Break + Pizza ðŸ•                              |
      | 20:30 | Talk 3                                        |
      | 21:00 | Closing words                                 |
      | 21:30 | Venue closing                                 |
      EOF
      sed -i '' \
        -e 's@{\\@{@g' \
        "$event_file"

      code $event_file

  create_reminders:
    desc: Create reminders for the next upcoming event (dynamically finds the closest future date)
    cmds:
      - task: internal:reminder_rfp
        vars:
          event_date: "{{.upcoming_event_date}}"
          event_sponsor: "{{.upcoming_event_sponsor}}"
      - task: internal:reminder_event
        vars:
          event_date: "{{.upcoming_event_date}}"
          event_sponsor: "{{.upcoming_event_sponsor}}"

  internal:reminder_rfp:
    desc: Prepare a reminder to submit RFP for the next event
    silent: true
    requires:
      vars:
        - event_date
        - event_sponsor
    cmd: |
      raw_date="{{.event_date}}"
      date_formatted=$(echo "${raw_date:0:4}-${raw_date:4:2}-${raw_date:6:2}")
      mkdir -p reminders
      rm reminders/*_rfp_linkedin.txt 2>/dev/null || true
      cat << EOF >> reminders/{{.event_date}}_rfp_linkedin.txt
      Hi #NLNAM community!

      We have the next meetup scheduled on $date_formatted with the help of #{{ .event_sponsor }}.
      We are looking for speakers to present at the event.

      If you have a nice topic you'd like to share with the community, please submit a presentation proposal using:
      {{.rfp_form_url}}

      If you know someone that should give a talk, please share this message with them!

      See you at the meetup!

      More info at {{.site_url}}
      EOF
      echo "RFP reminder created at reminders/{{.event_date}}_rfp_linkedin.txt"

  internal:reminder_event:
    desc: Prepare a reminder for the next event
    silent: true
    requires:
      vars:
        - event_date
        - event_sponsor
    cmd: |
      raw_date="{{.event_date}}"
      date_formatted=$(echo "${raw_date:0:4}-${raw_date:4:2}-${raw_date:6:2}")

      mkdir -p reminders
      rm reminders/*_event_linkedin.txt 2>/dev/null || true

      cat << EOF >> reminders/{{.event_date}}_event_linkedin.txt
      Hi #NLNAM community!

      We have the next meetup scheduled on $date_formatted with the help of #{{ .event_sponsor }}.
      If you haven't registered yet, please do so using: https://nlnam_{{.event_sponsor | lower}}.eventbrite.nl/

      At the same time we are always looking for speakers to present at the events.
      If you have a nice topic you'd like to share with the community, please submit a presentation proposal using:

      {{.rfp_form_url}}

      If you know someone that should give a talk, please share this message with them!

      See you at the meetup!

      More info at {{.site_url}}
      EOF
      echo "RFP reminder created at reminders/{{.event_date}}_event_linkedin.txt"
