version: "3"

vars:
  site_dir: website
  rfp_form_url: https://forms.gle/qmjaMqcHLuJV3rTy8

tasks:
  default: task -l

  build:
    desc: Build the site
    dir: "{{.site_dir}}"
    cmd: |
      export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
      uv run mkdocs build -v --strict -t material

  test:
    desc: Run the github test workflow with act
    cmds:
      - act -j test

  deploy:
    desc: Deploy the site to GitHub Pages branch
    cmds:
      - uv run mkdocs gh-deploy --force

  serve:
    desc: Serve the site
    dir: website
    cmd: |
      export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
      open http://localhost:8000/
      uv run mkdocs serve

  ### Initialize the repo
  init:
    desc: Initialize this repo install all dependencies for uv and mac
    cmds:
      - task: init:uv
      - task: init:mac

  init:uv:
    desc: Initialize this repo with python dependencies with uv
    cmds:
      - uv sync

  init:mac:
    desc: Initialize this repo with mac dependencies
    platforms:
      - darwin
    cmds:
      - brew install cairo freetype libffi libjpeg libpng zlib pngquant

  ### Create a post
  post:
    desc: Create a new event and open it in vscode
    aliases: [new]
    silent: true
    interactive: true
    cmd: |
      echo "Provide the date in format YYYY-MM-DD for the next event:"
      read event_date
      echo "Provide the sponsor of the next event (without spaces):"
      read event_sponsor
      echo "What is the website?"
      read event_website
      echo "What is the full address?"
      read event_address
      event_file="{{.site_dir}}/docs/events/dates/$(echo "$event_date" | sed 's/-//g')_${event_sponsor}.md"
      sponsors=$(sed 's/_/ \& /g' <<< "$event_sponsor")

      cat << EOF >> $event_file
      ---
      # draft: true
      date:
        created: {{ now.Format "2006-01-02" }}
        # updated: {{ now.Format "2006-01-02" }}
      title: NLNAM Meetup
      description: $event_date NLNAM Meetup event
      ---

      # NLNAM Meetup with $sponsors

      The next meetup is hosted by [$sponsors](https://$event_website) on $event_date.

      Thank you $sponsors for providing your office space to host us and fill our bellies with pizzas and drinks!

      * [Register for the event](https://nlnam_${event_sponsor}.eventbrite.nl/)
          * Registration ends on {\{ registration_closes("$event_date", 2) }} at 23:59.
      * [Submit a presentation proposal]({{.rfp_form_url}})

      ## Specifics
      * [OPTIONAL] **<u>Bring your ID</u>** to enter the Adyen building.
      * [OPTIONAL] We have a hard stop at 21:00. We will need to be outside the building by then.

      ## Location
      {\{ google_maps_link("$event_address") }}

      ## Agenda

      | Time  | Activity                                      |
      | ----- | --------------------------------------------- |
      | 18:00 | Doors open                                    |
      | 18:30 | Welcome + **$event_sponsor** sponsor talk     |
      | 19:00 | Talk 1                                        |
      | 19:30 | Talk 2                                        |
      | 20:00 | Break + Pizza 🍕                              |
      | 20:30 | Talk 3                                        |
      | 21:00 | Closing words                                 |
      | 21:30 | Be outside the building                       |
      EOF
      sed -i '' \
        -e 's@{\\@{@g' \
        "$event_file"

      task event_data=$event_date reminder_rfp
      task event_data=$event_date event_sponsor=$event_sponsor reminder_event
      code $event_file

  reminder_rfp:
    desc: Prepare a reminder to submit RFP for the next event
    silent: true
    requires:
      vars:
        - event_data
    cmd: |
      mkdir -p reminders
      cat << EOF >> reminders/{{.event_data}}_rfp_linkedin.txt
      Hi NLNAM community!

      We have the next meetup scheduled on {{ .event_data }} and we are looking for speakers to present at the event.

      If you have a nice topic you'd like to share with the community, please submit a presentation proposal using the link below:

      {{.rfp_form_url}}

      If you know someone that should give a talk, please share this message with them!

      See you at the meetup!
      EOF

  reminder_event:
    desc: Prepare a reminder for the next event
    silent: true
    requires:
      vars:
        - event_data
        - event_sponsor
    cmd: |
      mkdir -p reminders
      cat << EOF >> reminders/{{.event_data}}_event_linkedin.txt
      Hi NLNAM community!

      We have the next meetup scheduled on {{ .event_data }}.
      If you haven't registered yet, please do so using the link below: https://nlnam_{{.event_sponsor}}.eventbrite.nl/

      At the same time we are always looking for speakers to present at the events.
      If you have a nice topic you'd like to share with the community, please submit a presentation proposal using the link below:

      {{.rfp_form_url}}

      If you know someone that should give a talk, please share this message with them!

      See you at the meetup!
      EOF
