name: test build of mkdocs

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: test build of mkdocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          ignore-nothing-to-cache: true

      - name: Build mkdocs site
        run: |
          cd website
          uv run mkdocs build -v --strict
